name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check repository
      - name: Check repository
        uses: actions/checkout@v3
      # JDK 23 Setup
      - name: JDK 23 Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
      # Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven
      # Navigate to the lab3 directory
      - name: Change directory to lab3
        run: cd lab3
      # Build with Maven
      - name: Build with Maven
        run: mvn -f lab3/pom.xml clean install
      # Run tests
      - name: Run Tests
        run: mvn test
