name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check repository
      - name: Check repository
        uses: actions/checkout@v3
      # JDK 23 Setup
      - name: JDK 23 Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
      # Maven Setup
      - name: Maven Setup
        uses: actions/setup-java@v3
        with:
          maven-version: '3.9.1'
      # Build with Maven
      - name: Build with Maven
        run: mvn clean install
      # Run tests
      - name: Run Tests
        run: mvn test
